name: Deploy con AWS SAM

on:
  push:
    branches: [main]
  workflow_dispatch:  

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: '.' # Esto obliga a usar la raíz sin subcarpetas extras

      - name: Setup AWS SAM
        uses: aws-actions/setup-sam@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: sa-east-1

      - name: SAM Build
        # Usamos -t para apuntar directo al archivo en el lugar donde estemos
        run: sam build -t template.yaml

      - name: SAM Deploy
        run: |
          sam deploy --no-confirm-changeset \
            --stack-name pipeline-datos-gian \
            --resolve-s3 \
            --capabilities CAPABILITY_IAM \
            --region sa-east-1