name: Deploy Lambda Oficial

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar código del repo
        uses: actions/checkout@v4

      # 1. Sacamos el archivo de la subcarpeta (como ya veníamos haciendo)
      - name: Preparar archivo
        run: cp lambdas/test-git-gian-2/lambda_function.py ./lambda_function.py

      # 2. Configuración oficial de credenciales (Manejado por Amazon)
      - name: Configurar credenciales AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: sa-east-1

      # 3. Creamos el archivo ZIP manualmente (evita errores de compresión de terceros)
      - name: Crear paquete ZIP
        run: zip function.zip lambda_function.py

      # 4. Actualización directa vía AWS CLI
      # Este comando es "fire and forget": envía y no se queda trabado esperando estados
      - name: Desplegar código en Lambda
        run: |
          aws lambda update-function-code \
            --function-name test-git-gian-2 \
            --zip-file fileb://function.zip
