name: Deploy Lambda

on:
  push:
    branches:
      - main
  workflow_dispatch:  # <--- ESTO ES LO QUE AGREGAS PARA EL BOTÓN MANUAL

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: AWS Lambda Deploy
        uses: appleboy/lambda-action@v0.2.0
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: sa-east-1
          function_name: test-git-gian
          source: lambda_function.py
          project_path: lambdas/test-git-gian/
          debug: true
