name: Deploy Lambda Oficial

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar código del repo
        uses: actions/checkout@v4

      - name: Preparar archivo
        run: cp lambdas/test-git-gian-2/lambda_function.py ./lambda_function.py

      # Corregido: Usamos guiones medios (-) en lugar de bajos (_)
      - name: Configurar credenciales AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: sa-east-1

      - name: Crear paquete ZIP
        run: zip function.zip lambda_function.py

      - name: Desplegar código en Lambda
        run: |
          aws lambda update-function-code \
            --function-name test-git-gian-2 \
            --zip-file fileb://function.zip
